### ISSUE TITLE
Decouple version tag from the repo

### ISSUE THREAD

**Issue by surchs** [neurobagel/query-tool#111]
Right now we fetch the release number every time any user interacts with the App:

https://github.com/neurobagel/query-tool/blob/9d110ba31119673fe1b6410418e322f296de680b/src/components/Navbar.tsx#L9-L21

This will break real quick with some level of load - and even just from running the e2e test suite a couple of times:
![image](https://github.com/neurobagel/query-tool/assets/1302022/5b9b54c9-94ec-4bb5-b9d0-8d1f0362a9c9)

There is really no reason to fetch this at all! The purpose of string is to tell you what version **you** are running, not what version is available. So this number should get baked into the build of the tool and read at build time from the build context, not from the repository!

**Comment by surchs** [comment]
I think there is a related problem (without the same performance impact) because we pull the neurobagel logo live every time the app loads for a user - couldn't find the issue for that, so maybe we need to make one

**Comment by rmanaem** [comment]
> There is really no reason to fetch this at all! The purpose of string is to tell you what version you are running, not what version is available. So this number should get baked into the build of the tool and read at build time from the build context, not from the repository!

I agree that it's better to have this baked in somewhere instead of pulling from the repo every time but having it hardcoded and having to update it every time a new release is made seems inefficient.

**Comment by surchs** [comment]
Agree, we'd need something that runs automatically at release time, but only once

**Comment by surchs** [comment]
Addressed in #390
