### ISSUE TITLE
Make UI responsive for smaller screens

### ISSUE THREAD

**Issue by surchs** [neurobagel/query-tool#122]
# Context
Right now the tool works best on desktop screen sizes. On smaller screens it scales down until Ui elements overflow their boxes - and look bad.

Because we use tailwind it should be easy to stack the query form on top of the response container when the screen size is smaller. That should already help.

# Why
- right now the app looks not very nice outside of a certain range of (pretty wide) screen width
- have a good basis to keep the app responsive (i.e. in the future we don't want to have responsiveness issues come back)
- have all UI elements be reasonably spaced apart so they don't overlap / touch

# Outcomes

- [x] If I make the screen very narrow, UI elements do not overlap
- [x] UI elements go from double-column layout to a narrow-screen appropriate layout
- [x] when I navigate to the query tool with a mobile-sized screen, I get some clear indication that the screen size is not supported (we probably want to figure out what screen sizes we want to / should support)

# What

- [ ]

**Comment by Sauradip07** [comment]
I want to work on this issue

**Comment by surchs** [comment]
Hey @Sauradip07, cool, thanks. Feel free to open a draft pr where we can look at the changes together!

The main idea here is to have the query form on the left side collapse into a menu or attack on top of the results on smaller screen's.

**Comment by surchs** [comment]
https://github.com/user-attachments/assets/0ddc45b8-85eb-4c93-8a16-1339dfbecbbd

With the new changes, there seems to be a new / exacerbating issue of elements getting spaced out further once they start collapsing on the screen size. I'd say it'd be worth looking into the responsiveness here to make the elements not do that.
@rmanaem wdyt?

**Comment by surchs** [comment]
@rmanaem, please take a look at the work pieces up there and add what you think is missing.
