### ISSUE TITLE
Fix the condition for `fail` case `nodes_response_status` from federation API

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/query-tool#125]
federation API returns `fail` not `failure` when all queried nodes fail. 

To address we need to:

- [x] Update `ResultContainer`
- [x] Update mock responses
- [x] Update `App`

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.2.1`](https://github.com/neurobagel/query-tool/releases/tag/v0.2.1) :rocket:
