### ISSUE TITLE
[BUG] Pointing query tool at n-API in federation mode breaks

### ISSUE THREAD

**Issue by surchs** [neurobagel/query-tool#149]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Expected Behavior

it works

### Current Behavior

it doesn't

### Error message

same error as we have encountered in https://github.com/neurobagel/query-tool/issues/138 before

### How to reproduce

- start query tool in "federation mode"
- set `NB_API_QUERY_URL` in `.env` to a node-API
- access the query tool and run a query

**Comment by rmanaem** [comment]
Since the query tool only supports federation mode, this behavior is expected see #239
