### ISSUE TITLE
Ensure apiQueryURL ends in slash in the entire app, not just when sending a query

### ISSUE THREAD

**Issue by surchs** [neurobagel/query-tool#22]
in neurobagel/query-tool#212 we added an automatic adding of a slash to the query URL:

https://github.com/neurobagel/old-query-tool/blob/81a690fd74e0c08a95079a26622f4d4ed018517a/components/QueryForm.vue#L153-L158

but this only affects the sending of the queries, not the overall apiQueryURL (e.g. for listing the nodes and options):

https://github.com/neurobagel/old-query-tool/blob/81a690fd74e0c08a95079a26622f4d4ed018517a/nuxt.config.js#L55-L58

We should make sure we add a slash if one is missing at the deepest level (maybe even immediately when we read the .env file)

**Comment by samadpls** [comment]
Hi @surchs , Following up on the previous [pull request](https://github.com/neurobagel/old-query-tool/pull/378), what additional requirements need to be addressed for this issue? 😋

**Comment by rmanaem** [comment]
Hi @samadpls,
This issue has been addressed in the new tool but we currently don't have a test for it. If you're interested in writing a test for it please see https://github.com/neurobagel/query-tool/issues/61
