### ISSUE TITLE
Fix the tests to run in node mode

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/query-tool#225]
Following neurobagel/query-tool#223 we discovered that we've been running our tests only in federation mode and neglecting node mode. This has lead to the code becoming specific to the responses coming from federation API so many of the types, response mocks, and tests assertions are specific to query tool pointing at a federation api.

To address this we need to make adjustments to make the tests pass in the node api mode or some cases don't run certain tests that are specific federation api mode.

We also need to run tests in node API mode in our workflows.

**Comment by surchs** [comment]
Hey @rmanaem, good catch. But I'm not convinced we want to keep maintaining both query -> f-api and query -> n-api. Especially in cases like this one where have to spend time to keep both modes in sync with each other. 

Maybe this would be a good time to discuss which of the two modes we want to keep supporting.

**Comment by rmanaem** [comment]
Following a discussion, it was decided that moving forward the query tool will only talk to a federation API and required changes will be addressed in neurobagel/planning#158 and as a result we can close neurobagel/query-tool#223 and neurobagel/query-tool#224
