### ISSUE TITLE
Find more descriptive ENV and var name for app root path

### ISSUE THREAD

**Issue by surchs** [neurobagel/query-tool#236]
I think we should find a more descriptive name for `NB_QUERY_URL_PATH`, especially for the internal variable name `queryURLPath` because when I see that in the codebase I am immediately thinking of a parameter I will include in a request to the f-API.

_Originally posted by @surchs in https://github.com/neurobagel/query-tool/pull/227#pullrequestreview-2213867467_

**Comment by rmanaem** [comment]
How about `NB_QUERY_APP_BASE_PATH` for the env var and `appBasePath` for the var itself?
