### ISSUE TITLE
Update husky scripts

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/query-tool#237]
When pre-commit runs, we get:
```bash
husky - DEPRECATED

Please remove the following lines from your hook scripts:

#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

They WILL FAIL in v10.0.0
```

**Comment by alyssadai** [comment]
Possibly related (?): when I run `npx husky install` following https://github.com/neurobagel/query-tool?tab=readme-ov-file#developer-setup, I get the message:

```bash
install command is DEPRECATED
```

I'm not sure if this actually indicates that the installation failed or not 🤷
