### ISSUE TITLE
Allow querying for pipeline name and version

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/query-tool#282]
- [x] Add two new dropdown fields for pipeline name and version (should have an extra/default option meaning "all available versions")
  - [x] Once user selects a pipeline name, the version dropdown options should update to be available vers for that pipeline
- [x] #293
- [x] Add pipeline name and version to downloadable results files

**Comment by rmanaem** [comment]
Requires 

- https://github.com/neurobagel/api/issues/344, 
- https://github.com/neurobagel/federation-api/issues/113, and 
- https://github.com/neurobagel/federation-api/issues/117
