### ISSUE TITLE
Discuss whether we want to use the `eslint-config-airbnb-typescript` fork

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/query-tool#290]
Since the original [`eslint-config-airbnb-typescript`](https://github.com/iamturns/eslint-config-airbnb-typescript) has been archived, we need to discuss and decide whether we want to go with a [fork of the project](https://github.com/Kenneth-Sills/eslint-config-airbnb-typescript) or look for another typescript config for eslint. 

Our options:
1. Do nothing and never upgrade to the new eslint(?)
2. Change our eslint airbnb style guide to the [new fork by Kenneth Sills](https://github.com/Kenneth-Sills/eslint-config-airbnb-typescript) 
3. Stop using airbnb altogether, i.e. rely only on the react-default and prettier rules
4. Move to the google style guide (which seems to support typescript): https://github.com/google/gts
5. Create and maintain our own eslint rule set. 
6. Use something opinionated like https://github.com/xojs/xo (looks like black in python land)

**Comment by surchs** [comment]
Decision:
- We will go with kenneth's fork
- we will check why we suddendly get new errors from eslint e.g. here: https://github.com/neurobagel/query-tool/pull/289
- we will check that Kenneth's fork / the typescript additions do not set any style rules but just add the necessary typescript support to the existing style rules maintained by airbnb

**Comment by surchs** [comment]
Taking another look, the new linting errors have appeared here: https://github.com/neurobagel/query-tool/pull/289/commits/6eb82a8df1b88a47e9d6ad87dca58ecf83e4c58d

The only change was moving to kenneth's TS-airbnb fork. The errors are from eslint, not from prettier - and we also didn't reformat our code. So it looks a lot like

- some style rules are defined in the TS-airbnb plugin
- Kenneth's fork has different style rules than what the archived / old TS-airbnb plugin had.

Let's figure this out before we merge

**Comment by surchs** [comment]
Still not fully getting it, but I notice this recent change / addition:

https://github.com/Kenneth-Sills/eslint-config-airbnb-typescript/blame/b22bb83b057370c169cb975bca9b69b674f99940/lib/shared.js#L9

**Comment by rmanaem** [comment]
Yea, came across this in the first PR:
https://github.com/Kenneth-Sills/eslint-config-airbnb-typescript/commit/932dea1002add959eddd3d3fde9be4e281db1c43#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5R1

Checked out the stylistic eslint plugin and I believe that is the cause of these new stylistic errors:
https://eslint.style/packages/default#install

**Comment by rmanaem** [comment]
Add a comment above the ignore statements in the eslint config file to clarify why we're ignoring them and the PR can go in.
