### ISSUE TITLE
Replace the latest version tag with a baked-in version

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/query-tool#291]
If an older version of the tool is deployed, the current implementation still uses the latest release tag. This needs to be replaced with the baked-in version.

 https://github.com/neurobagel/query-tool/blob/0ccfd0ac71bf5c1cca17c3ee7491283ced2df228/src/components/Navbar.tsx#L38-L49

TODO:

- [ ] Figure out how to obtain the version number **during** the Docker image build process (e.g. from GH)
- [ ] Make sure the obtained version number is of the **new release**, i.e. if build happens as part of release, make sure the number is of the new/future release, not the previous one
- [ ] For nightly builds: make sure the version number is nightly
- [ ] Also include a commit sha in the version so we can differentiate nightly deployments
- [ ] Bake this information into the docker image so that every time we deploy a tool from this image, it'll display the correct version number
- [ ] Write a test that checks that the version number is something we can now control directly (e.g. ENV var, hard-coded, whatever it ends up being)
- [ ] Manually test this by triggering a new build (e.g. nightly) and then deploying off of the docker image and confirming the version number

Note:
- preview deployments during PRs via netlify will probably not work like this
- also local dev environments / bare metal installs may not have access to the same information / context so we need to decide what they should show as versions. Ideally something very noticeable so if we ever see it in prod, we know something is wrong

**Comment by surchs** [comment]
An example of this happening right now: https://neurobagel-alliancefrqs.douglasneuroinformatics.ca/querytool?node=All

**Comment by rmanaem** [comment]
So the options I mentioned during stand-up:

- Use the version field in package.json to manually hardcode the version
- Write a workflow to run on release to update the version on the UI

Either of these will solve the issue for the latest release versions but not the nightly.

@surchs You mentioned something about having GitHub SHA for the nightly builds, could you elaborate?

**Comment by surchs** [comment]
@rmanaem What I mean is that `latest` is always just an alias for a named release version (e.g. right now `latest == v0.7.0`). So displaying that named version somewhere on the UI of the tool should be enough for us to understand quickly what version of our tool someone is running.

By contrast `nightly` is not an alias of a named release but rather just points at the HEAD of the main branch. And because that moves very often, just writing `nightly` as the version on the tool is not helpful. So I am suggesting to instead/in addition write the git commit SHA of HEAD when the image was built. Something like so:

![Image](https://github.com/user-attachments/assets/eb848b42-753f-4f93-a0b3-9d7c9a7fd7f3)

Now I can at least look for this SHA in our git log to figure out what someone is running.

**Comment by rmanaem** [comment]
This seems a bit tricky. If we were to go back to the two options mentioned and adopt them for nightly:
- Manually updating the version on PRs wouldn't be pointing to the latest SHA of the main since we squash
- Using a workflow to overwrite the version on merge to main with the latest SHA of the main also wouldn't be pointing to the latest but rather the one before the latest since this change itself would be creating another commit

**Comment by surchs** [comment]
I think that's a bit overly complex, no? For releases, it makes sense to (semi-)manually update the version in package.json as part of the release process (may have to be exact when and how that happens, i.e. only in the actual release PR)

But for nightly I don't need a physical record of the git SHA in the repo - git already does that for me! So there's no need to commit any "I overwrite version with current git SHA" to version control itself.

Why not: 
- I am about to rebuild docker image for nightly tag
- I check current HEAD SHA of main branch
- As part of GH workflow, I store this value as a ENV variable (or find/replace in package.json if absolutely required)
- I finish building the image
- I'm done

Wouldn't that work?

**Comment by rmanaem** [comment]
That should work.

**Comment by rmanaem** [comment]
The only problem would be if we have it in the same workflow as the nightly docker build, it would overwrite the latest version number since the workflow runs on merge to main but I'll see if I can add a condition to skip the workflow if there was a release tag in the PR.

**Comment by rmanaem** [comment]
For latest (release):
- Increment the version in package.json as part of the release to match that of GitHub
- Commit the change in version
- Trigger the deploy workflow

**Comment by rmanaem** [comment]
For the nightly:
- Increment the version using the latest SHA
- don't commit
- build the image
- include the sha in the nightly image metadata
