### ISSUE TITLE
Neurobagel on Ubuntu 24.04 "Failed to retrieve Node options" in query

### ISSUE THREAD

**Issue by seanhatton** [neurobagel/query-tool#310]
I have been testing Neurobagel on Ubuntu 24.04. It seems to install and run ok, but when I open the query (localhost:3000) I get an error "Failed to retrieve Node options" - I can only see the "All" graph option and not the subordinates (e.g OpenNeuro, Quebec Parkinson's etc.). This isn't a problem on Ubuntu 22.04, is Neurobagel compatible with 24.04? If I do a query I get the same hits between Ubuntu versions (i.e. both get 'All' data sources).

**Comment by surchs** [comment]
Hey @seanhatton. Can you please provide a little more detail to help us understand what you have done and what is not working now. Did you follow the steps here: https://neurobagel.org/getting_started/? 

>  can only see the "All" graph option and not the subordinates (e.g OpenNeuro, Quebec Parkinson's etc.).

What profile are you using to launch your neurobagel stack? https://neurobagel.org/config/#available-profiles 
If you use a full-stack profile we would expect at minimum to see your local graph in the list of available nodes. Do you see any nodes? What does an empty query return as results?

> This isn't a problem on Ubuntu 22.04

Again, this is quite hard to evaluate in isolation. I don't know if you have done the same setup, using the same versions of the tools.

> is Neurobagel compatible with 24.04

We strongly recommend you deploy Neurobagel from the official docker images. I don't think there should be any difference between Ubuntu 22.04 and 24.04 in whether you can deploy these images. If that's what you're experiencing, it'd be good to have some more detail to replicate that.

**Comment by seanhatton** [comment]
Close this issue, conflict with old nodejs v16 installation. All good on Ubunutu 24.04.

**Comment by surchs** [comment]
Before we close the issue: @seanhatton could you explain how you were trying to deploy the Neurobagel node so others may benefit from your experience? It sounds like you were installing the tools directly on your machine as opposed to using the docker images, is that correct?

> conflict with old nodejs v16 installation

Which tool did you try to install with node 16? We generally don't test across node versions because we expect people to deploy from our docker images. But it would still be good to know what broke.

Thanks

**Comment by seanhatton** [comment]
I think I originally thought nodejs 16 was a prerequisite (bare metal
install) but I reread the current instructions and removed that step. I am
running a full stack on the recipes folder.
