### ISSUE TITLE
Create a complete test environment with docker compose

### ISSUE THREAD

**Issue by surchs** [neurobagel/query-tool#316]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### New feature

When I start developing on the query tool, I want to be able to launch all other services I depend on with docker compose, so that I save myself the hassle of pulling images and spinning up services by hand every time.

**Comment by alyssadai** [comment]
@rmanaem, if you're not already doing so, want to include as part of this issue the Dependabot config update to ensure submodules are auto-updated?
