### ISSUE TITLE
[BUG] Can't download Datalad datasets

### ISSUE THREAD

**Issue by seanhatton** [neurobagel/query-tool#324]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

I am using the web-based query tool to select some datasets: some from Datalad and some from github.  Using the Neurobagel DATAGET service I want to download the raw data and associated metadata (e.g. participant.tsv). 

### Current Behavior

Using Neurobagel DATAGET I can download the github study files but not the Datalad studies. It gets the folder structure but no files. Opening the dataset-level-results.tsv, browsing the PortalURI for a Datalad dataset (e.g. https://datasets.datalad.org/abide/RawDataBIDS/CMU_b) shows directory structure but no files (e.g. participants.tsv, NIFTIs). Browsing Datalad.org the files are there.

### Error message

All files have a red cross on the icon. With a Datalad dataset, when you click to open (e.g. participants.tsv) it says the file cannot open because the link is broken. With OpenNeuro the participants.tsv is downloaded and accessible. 

### Environment

- OS: Ubuntu 24.04
- Python version: 3.9

### How to reproduce

In the query tool select a dataset "from International Neuroimaging Data-sharing Initiative" then use the DATAGET function to clone the files down. Open the downloaded content and see if the files at the root of the dataset directory structure are downloaded or a broken link.

**Comment by surchs** [comment]
Going to see if we can't resolve this by finally integrating Remi's cohort creator now: https://github.com/neurodatascience/cohort_creator/issues/117

**Comment by surchs** [comment]
Moving to tracked until I had a chance to chat with Remi about the way forward

**Comment by surchs** [comment]
Hi @seanhatton, thanks for the bug report. It seems our data getter tool had not been updated to the most recent schema for the query results. For now this is fixed, and I will close the issue. 

But as the data getter tool was not meant to be around for very long, we will separately address the underlying issue of migrating to a more robust and well maintained data getter tool.
