### ISSUE TITLE
`AVAILABLE PIPELINES` hover on results card looks a little strange when there's no pipeline data

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/query-tool#334]
When a matching dataset for a query doesn't have any info on available pipelines, the hover text appears as a little blank bubble, which unfortunately looks like a UI bug rather than something intentional.

![Image](https://github.com/user-attachments/assets/edc4eafd-33e9-484b-a3ed-5d7d6ce8dea1)

Suggestions:
- Maybe we could display the word "None" in the bubble when there's no pipeline info? Or just disable the hover in those cases?

**Comment by surchs** [comment]
I'd vote to hide or grey out the button if no pipelines are available

**Comment by rmanaem** [comment]
I could also modify the text to say `no pipelines available` on the button

**Comment by surchs** [comment]
how about just `no pipelines` and `available pipelines`?
