### ISSUE TITLE
make the participants-results table nice for humans and machines

### ISSUE THREAD

**Issue by surchs** [neurobagel/query-tool#356]
The query tool let's you download information about cohorts you find. We have two kinds of users in mind for this information:

1. human users, who likely want to look at the downloaded information to learn more about their cohort
2. machines or tools who want to use the information to provide services to their own users, e.g. to download a cohort to the users computer (or create symlinks https://github.com/neurobagel/planning/issues/188)

Right now our downloadable files do a little bit of both, and neither very nicely (e.g. include many fully expanded IRIs etc). We mainly want to make sure that 

- [x] there is one file that includes information about the cohort in a nice-for-humans format
- [x] there is *another* file that includes enough information for tools like cohort-creator to keep doing what they are doing

And to achieve this, we are willing to have a bit of duplication in these files.

Here is a draft of both formats for us to discuss: https://docs.google.com/spreadsheets/d/1rLgbzZv1AqgYTGglI3yuQVdOM1bbYvvY8ijmbTXsfHg/edit?usp=sharing

TODO

- [x] Discuss and agree on a first format for the human and machine readable files
- [x] Pick an intuitive name for both files
- [x] Implement the new file formats in the query tool
- [x] Update the query tool examples in neurobagel/examples (discuss / decide what to do with the old examples)
- [ ] Ping Remi in cohort-creator land about the upcoming change to the format of these files
- [ ] Deploy / Release the new query tool version

**Comment by alyssadai** [comment]
One more thought: how about changing the current column name `SessionFilePath` to `SessionPath`, to better reflect what the path points to?

**Comment by surchs** [comment]
I believe we previously used `SessionPath`. It seems like a better name to me as well, but before we switch it again, we should look up what the previous switch reason was

**Comment by surchs** [comment]
The change from `SessionPath` to `SessionFilePath` came in #112, but I don't see a reason given. So let's make sure that if we change the name now, we list our reason clearly in the PR
