### ISSUE TITLE
Refine content and location of "How to get data" button/modal

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/query-tool#369]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### New feature
- Location: make it visible at all times
  - It is a bit inconvenient that currently, in order to view the instructions for downloading data, I have to first run a query (and then wait for it to complete). Instead of this, having the "How to get data" button be visible all the time may be more user friendly, and also makes it easier for us to demonstrate query tool capabilities. It is clear enough from the modal contents that any data-getting steps only apply once you have run a query.
  - We have received a suggestion to put it in the top right corner, maybe next to the external link buttons

- Content:
  - [x] Rename button to "How to **access** data, maybe?
  - [x] Retitle DataLad section to "Downloading matching source data results using Datalad" or similar
  - [x] Remove section on "Results file for data access or programmatic use" - this is probably not needed anymore
  - [ ] Maybe add a section "About the results files" that mentions that both include the same info and columns, just in two different formats, and either can be used with a script for downloading the data of matching subjects to your local filesystem

**Comment by surchs** [comment]
We want to discuss this together as a team to get a test run for generic UI design work

**Comment by surchs** [comment]
@alyssadai please put a screenshot of what you have in mind

**Comment by alyssadai** [comment]
Here's my suggestion of where to put the button, based on feedback from our OBI friends as well (see the red box!)
<img width="949" alt="Image" src="https://github.com/user-attachments/assets/a9aec9a6-ff15-480a-a59f-0fbe2cad4f53" />

LMKWYT :)

**Comment by surchs** [comment]
I would prefer to keep it below the nav-bar and instead move the results section down a little bit. My main reason is that it would maintain our like-goes-with-like setup to the layout: navbar is generally for going to secondary sources (and login), below that is for interacting with the app. 

Maybe we could even pull up the "Submit query" button and just have all of them sit on top of the results like so:

![Image](https://github.com/user-attachments/assets/1377ec1d-893a-42c3-a00f-5ff226c6934e)

**Comment by alyssadai** [comment]
@surchs, having the "How to get data" button above the results section looks fine to me.

I'd vote to keep "Submit query" and the download results button where they currently are (with download results only being visible once the query results are returned), since I think that provides a more natural flow for a user.

**Comment by rmanaem** [comment]
Question, would there be a scenario where the user would want to access the `How to get data` button before submitting a query or before seeing the results?

**Comment by rmanaem** [comment]
![Image](https://github.com/user-attachments/assets/839ff3a1-0523-4ae2-a8fb-ca62335f118c)

**Comment by rmanaem** [comment]
@neurobagel/dev This is what the content of the dialog looks like after changes, is there anything you'd like to change or add?
![Image](https://github.com/user-attachments/assets/719abb9d-3a4b-41ff-bbf5-1d1039ed32d6)

**Comment by alyssadai** [comment]
Thanks @rmanaem! 

- Since either results file should be able to be used with the DataLad script (or BIC symlink script), I'd update point 2. to something like:
  > 2. Download one of the query results files using the "Download selected query results" dropdown
- maybe update the docker command snippet so the name of the file isn't hardcoded? e.g., `data/<your-query-results-file>`
- Update the warning so it doesn't refer to "results file downloadable above" - maybe just "...write your own script that uses the paths from a results file".

**Comment by surchs** [comment]
> maybe update the docker command snippet so the name of the file isn't hardcoded? e.g., data/<your-query-results-file>

I vote (strongly) against this specific point. It would mean a user can no longer copy-paste the command but instead must find the part of the command they need to change and then change it. So let's stick with one file name (I'd vote for the human-readable one, because they'll download that by default).

**Comment by alyssadai** [comment]
Okay, good point @surchs! That sounds good. Do you agree with the other suggestions?

**Comment by alyssadai** [comment]
@surchs, to be clear though - if you run >1 query and download the results each time, you might already run into a situation where the default docker command no longer works, since the downloaded file will have `(1)`, `(2)`, etc. at the end (at least on Windows) if you're downloading to the same location.

**Comment by surchs** [comment]
> Okay, good point [@surchs](https://github.com/surchs)! That sounds good. Do you agree with the other suggestions?

yes, agree with the other points!  

> [@surchs](https://github.com/surchs), to be clear though - if you run >1 query and download the results each time, you might already run into a situation where the default docker command no longer works, since the downloaded file will have `(1)`, `(2)`, etc. at the end (at least on Windows) if you're downloading to the same location.

that's true - but that's a common enough problem with repeat downloads. So I don't think we need to point that out / address it separately.
