### ISSUE TITLE
Add back extra download button for the URI-based query result file

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/query-tool#387]
I would suggest renaming the buttons to something like:

`Download selected query results` (file with descriptive labels)

and

`Download selected query results with URIs` (file w/ URIs)
- ideally, on hover, this could contain a brief description such as "For details on controlled terms in the harmonized results" or something for a less technical user 

TODO

- [ ] Have a button with `cohort results` label and a download icon
- [ ] Have a button with `machine cohort results` label  and download icon
- [ ] ~~Have a hover tooltip (hover on button or hover on little `?` icon near button) that explains briefly what both files are. Essentially: "You probably want the `cohort results` file unless you do fancy stuff)~~
- [ ] optional: make both buttons in one button (split button) and default to the "human" file

**Comment by surchs** [comment]
Let's use something like a split button and default to the human file: https://mui.com/material-ui/react-button-group/#split-button
![Image](https://github.com/user-attachments/assets/6ffa4c80-d1e5-4503-acb3-487a7e440a72)

**Comment by rmanaem** [comment]
_Originally posted https://github.com/neurobagel/query-tool/issues/389#issuecomment-2523714070_

Hey @neurobagel/dev, a quick additional thought on this I realized we didn't discuss in https://github.com/neurobagel/query-tool/issues/376 .

How do we feel about renaming the results files to something clearer, now that we no longer have dataset and participant files:

One suggestion:

    cohort-participant-machine-results.tsv -> neurobagel-query-results-with-URIs.tsv
    cohort-participant-results.tsv -> neurobagel-query-results.tsv

Goal would be that a user should be able to:

    Easily identify which files are Neurobagel query tool results files within their own FS
    Know, semi-intuitively, based off the title what the files contain (ideally, they would convey that they are the same info, just in two different representations)
