### ISSUE TITLE
[BUG] Failed to retrieve Node options

### ISSUE THREAD

**Issue by seanhatton** [neurobagel/query-tool#391]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

I am on Ubuntu 22.04 trying to run the query tool on localhost:3000. 

### Current Behavior

Loading localhost:3000 I get an error "Failed to retrieve Node options" and I can't query any node.

### Error message

"Failed to retrieve Node options"

### Environment

- OS: Ubuntu 22.04
- Python/Node version: 3.9

### How to reproduce

Run the full stack Docker profile, open a web browser to localhost:3000 and error occurs.

### Anything else?

My port 8080 was bound to a TCP port. I killed that process so the port is free. I also amended the .env for the NB_FAPI_PORT_HOST=8081 and NB_API_QUERY_URL=https://localhost:8081 with the same behavior. Running neurobagel in a virtual machine works.

**Comment by surchs** [comment]
Thanks @seanhatton. Could you provide 
- the output of `docker compose config`? 
- the content of your `local_nb_nodes.json` file

And just to clarify, you are trying to set things up on your local workstation (Ubuntu22) by following our https://neurobagel.org/user_guide/getting_started/ instructions with docker? I suspect something is not correctly configured, but that'll be easier to spot with the extra content. 

edit: oh and please also include the exact command you use to launch the stack (e.g. if you use a different profile than the default)

**Comment by seanhatton** [comment]
**************************************************************
**docker-compose.yml**
**************************************************************

services:

  api:
    image: "neurobagel/api:${NB_NAPI_TAG:-latest}"
    profiles:
      - "local_node"
      - "full_stack"
    ports:
      - "${NB_NAPI_PORT_HOST:-8000}:8000"
    environment:
      NB_GRAPH_USERNAME: ${NB_GRAPH_USERNAME}
      NB_GRAPH_ADDRESS: graph
      NB_GRAPH_PORT: 7200
      NB_GRAPH_DB: ${NB_GRAPH_DB:-repositories/my_db}
      NB_RETURN_AGG: ${NB_RETURN_AGG:-true}
      NB_API_PORT: 8000
      NB_API_ALLOWED_ORIGINS: ${NB_NAPI_ALLOWED_ORIGINS}
      NB_ENABLE_AUTH: ${NB_ENABLE_AUTH:-false}
      NB_QUERY_CLIENT_ID: ${NB_QUERY_CLIENT_ID}
    volumes:
      - "./scripts/api_entrypoint.sh:/usr/src/api_entrypoint.sh"
    entrypoint:
      - "/usr/src/api_entrypoint.sh"
    secrets:
      - db_user_password

  graph:
    image: "ontotext/graphdb:10.3.1"
    profiles:
      - "local_node"
      - "full_stack"
    volumes:
      - "graphdb_home:/opt/graphdb/home"
      - "./scripts:/usr/src/neurobagel/scripts"
      - "./vocab:/usr/src/neurobagel/vocab"
      - "${LOCAL_GRAPH_DATA:-./data}:/data"
    ports:
      - "${NB_GRAPH_PORT_HOST:-7200}:7200"
    environment:
      NB_GRAPH_USERNAME: ${NB_GRAPH_USERNAME}
      NB_GRAPH_PORT: 7200
      NB_GRAPH_DB: ${NB_GRAPH_DB:-repositories/my_db}
    entrypoint:
      - "/usr/src/neurobagel/scripts/setup.sh"
    working_dir: "/usr/src/neurobagel/scripts"
    secrets:
      - db_admin_password
      - db_user_password

  federation:
    image: "neurobagel/federation_api:${NB_FAPI_TAG:-latest}"
    profiles:
      - "local_federation"
      - "full_stack"
    ports:
      - "${NB_FAPI_PORT_HOST:-8080}:8000"
    volumes:
      - "./local_nb_nodes.json:/usr/src/local_nb_nodes.json:ro"
    environment:
      NB_API_PORT: 8000
      NB_FEDERATE_REMOTE_PUBLIC_NODES: ${NB_FEDERATE_REMOTE_PUBLIC_NODES:-True}
      NB_ENABLE_AUTH: ${NB_ENABLE_AUTH:-false}
      NB_QUERY_CLIENT_ID: ${NB_QUERY_CLIENT_ID}

  query_federation:
    image: "neurobagel/query_tool:${NB_QUERY_TAG:-latest}"
    profiles:
      - "local_federation"
      - "full_stack"
    ports:
      - "${NB_QUERY_PORT_HOST:-3000}:5173"
    environment:
      NB_API_QUERY_URL: ${NB_API_QUERY_URL}
      NB_QUERY_APP_BASE_PATH: ${NB_QUERY_APP_BASE_PATH:-/}
      NB_ENABLE_AUTH: ${NB_ENABLE_AUTH:-false}
      NB_QUERY_CLIENT_ID: ${NB_QUERY_CLIENT_ID}

secrets:
  db_admin_password:
    file: ${NB_GRAPH_SECRETS_PATH:-./secrets}/NB_GRAPH_ADMIN_PASSWORD.txt
  db_user_password:
    file: ${NB_GRAPH_SECRETS_PATH:-./secrets}/NB_GRAPH_PASSWORD.txt

volumes:
  graphdb_home:


**************************************************************
**local_nb_nodes.json**
**************************************************************

[
    {
        "NodeName": "ReproLake",
        "ApiURL": "http://api:8000"
    }
]

**************************************************************

**Comment by surchs** [comment]
Hey @seanhatton. It seems you pasted the **content** of our docker-compose.yml file. Could you please instead post the output of running 

```bash
docker compose config
```
in your terminal when you are in the project directory.

And please also confirm how you are launching the stack, i.e. the exact `docker compose up` command you run

**Comment by seanhatton** [comment]
I am running the full stack docker: docker compose --profile full_stack up -d

** Config **

```
WARN[0000] The "NB_QUERY_CLIENT_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "NB_QUERY_CLIENT_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "NB_QUERY_CLIENT_ID" variable is not set. Defaulting to a blank string. 
name: neurobagel_node
services:
  api:
    profiles:
      - local_node
      - full_stack
    entrypoint:
      - /usr/src/api_entrypoint.sh
    environment:
      NB_API_ALLOWED_ORIGINS: '*'
      NB_API_PORT: "8000"
      NB_ENABLE_AUTH: "false"
      NB_GRAPH_ADDRESS: graph
      NB_GRAPH_DB: repositories/my_db
      NB_GRAPH_PORT: "7200"
      NB_GRAPH_USERNAME: DBUSER
      NB_QUERY_CLIENT_ID: ""
      NB_RETURN_AGG: "true"
    image: neurobagel/api:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
    secrets:
      - source: db_user_password
    volumes:
      - type: bind
        source: /home/sehatton/Desktop/recipes/scripts/api_entrypoint.sh
        target: /usr/src/api_entrypoint.sh
        bind:
          create_host_path: true
  federation:
    profiles:
      - local_federation
      - full_stack
    environment:
      NB_API_PORT: "8000"
      NB_ENABLE_AUTH: "false"
      NB_FEDERATE_REMOTE_PUBLIC_NODES: "True"
      NB_QUERY_CLIENT_ID: ""
    image: neurobagel/federation_api:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8000
        published: "8080"
        protocol: tcp
    volumes:
      - type: bind
        source: /home/sehatton/Desktop/recipes/local_nb_nodes.json
        target: /usr/src/local_nb_nodes.json
        read_only: true
        bind:
          create_host_path: true
  graph:
    profiles:
      - local_node
      - full_stack
    entrypoint:
      - /usr/src/neurobagel/scripts/setup.sh
    environment:
      NB_GRAPH_DB: repositories/my_db
      NB_GRAPH_PORT: "7200"
      NB_GRAPH_USERNAME: DBUSER
    image: ontotext/graphdb:10.3.1
    networks:
      default: null
    ports:
      - mode: ingress
        target: 7200
        published: "7200"
        protocol: tcp
    secrets:
      - source: db_admin_password
      - source: db_user_password
    volumes:
      - type: volume
        source: graphdb_home
        target: /opt/graphdb/home
        volume: {}
      - type: bind
        source: /home/sehatton/Desktop/recipes/scripts
        target: /usr/src/neurobagel/scripts
        bind:
          create_host_path: true
      - type: bind
        source: /home/sehatton/Desktop/recipes/vocab
        target: /usr/src/neurobagel/vocab
        bind:
          create_host_path: true
      - type: bind
        source: /home/sehatton/Desktop/recipes/data
        target: /data
        bind:
          create_host_path: true
    working_dir: /usr/src/neurobagel/scripts
  query_federation:
    profiles:
      - local_federation
      - full_stack
    environment:
      NB_API_QUERY_URL: https://localhost:8080
      NB_ENABLE_AUTH: "false"
      NB_QUERY_APP_BASE_PATH: /
      NB_QUERY_CLIENT_ID: ""
    image: neurobagel/query_tool:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5173
        published: "3000"
        protocol: tcp
networks:
  default:
    name: neurobagel_node_default
volumes:
  graphdb_home:
    name: neurobagel_node_graphdb_home
secrets:
  db_admin_password:
    name: neurobagel_node_db_admin_password
    file: /home/sehatton/Desktop/recipes/secrets/NB_GRAPH_ADMIN_PASSWORD.txt
  db_user_password:
    name: neurobagel_node_db_user_password
    file: /home/sehatton/Desktop/recipes/secrets/NB_GRAPH_PASSWORD.txt
```

**Comment by surchs** [comment]
On a first read I cannot see anything that looks clearly wrong. 

> and I can't query any node

does this mean you cannot query your own local node (called Reprolake). Or are you also unable to query any of our public nodes (e.g. INDI)? Or can you not even see these public nodes in the node dropdown?

Another possibility here is that you may have to pull our most recent docker images. Could you do this:

- `docker compose --profile full_stack down` followed by
- `docker compose --profile full_stack pull` and then
- `docker compose --profile full_stack up -d`

It's not super likely to be the cause because you should still have compatible (if outdated) images. If that doesn't fix your issue we would have to look a bit more in detail.

> Running neurobagel in a virtual machine works.

Interesting. How recently did you do the VM setup? If it works there, could you try to identify what you did differently

**Comment by surchs** [comment]
Also pinging @neurobagel/dev for extra pairs of eyes in case I am overlooking things

**Comment by seanhatton** [comment]
I pulled down the fresh docker image but getting the same issue. In the Graph dropdown menu I only have "All" so I can't see my local graph which I have uploaded with the vocab. Preparing to rebuild my workstation...

**Comment by seanhatton** [comment]
I re-downloaded the recipes folder and launched it again, working fine now. Maybe it was an incompatible/out-dated recipes folder.
