### ISSUE TITLE
[BUG] Selecting multiple nodes and deselecting "All" returns results for only last node

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/query-tool#77]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Expected Behavior

When I select the OpenNeuro, PPMI, and QPN nodes in the query tool and deselect "All", I expect any query results to be the same as when only "All" is selected.

### Current Behavior

When nodes are selected individually, I only get the query results for the last selected node.

### Environment

- OS:
- Python/Node version:

**Comment by rmanaem** [comment]
This has already been addressed.
