### ISSUE TITLE
Clear diagnosis dropdown entirely when healthy control is selected

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/query-tool#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

Currently, you can select a diagnosis value from the dropdown _and then_ select "Healthy Control", and the result will only show you the latter even though it looks like you have selected both.

While the tooltip over healthy control is very helpful (especially in the case where you have selected "healthy control" _first_, the fact that you can still do the above has still confused several users.

If it is not too difficult, we should simply clear the dropdown for "diagnosis" (regardless if any have been selected already) when the "healthy control" checkbox is clicked. This will indicate the exclusively of these two options a lot more clearly.

Related comments:
- https://github.com/neurobagel/old-query-tool/issues/93#issuecomment-1612209914
- https://github.com/neurobagel/old-query-tool/issues/93#issuecomment-1617462281

**Comment by rmanaem** [comment]
This has already been addressed during the refactor.
