### ISSUE TITLE
`NB_IS_FEDERATION_API` is not parsed correctly

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/query-tool#84]
The `NB_IS_FEDERATION_API` is currently being parsed as a `string` which in JS/TS as long as it is not an empty string is considered a truthy value therefore even when the env var is set to `false` it will be parsed as `true`.

https://github.com/neurobagel/query-tool/blob/99fc5c019054aff221280b37ab1a09886721134a/src/utils/constants.ts#L12-L13

**Comment by surchs** [comment]
I feel like this has come up before. Maybe in the API URL parsing?

**Comment by rmanaem** [comment]
Not in this tool. I believe we had an issue with Vue being opinionated about the capitalization of props.

**Comment by surchs** [comment]
No, I meant reading in ENV variables and having to deal with any string evaluating true. I can't remember where that was - but regardless, we can probably figure out a reasonable solution again.

**Comment by rmanaem** [comment]
> No, I meant reading in ENV variables and having to deal with any string evaluating true. I can't remember where that was - but regardless, we can probably figure out a reasonable solution again.

Sounds familiar but I don't recall that.
I think this is a simple fix https://stackoverflow.com/a/264037

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.2.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.2.0) :rocket:
