### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/query-tool#85]
At the moment the README.md only includes auto-generated instructions and needs to be updated to include our custom instructions and information similar to https://github.com/neurobagel/old-query-tool/blob/main/README.md

**Comment by Sauradip07** [comment]
Can i work on this issue please

**Comment by rmanaem** [comment]
@Sauradip07 Unfortunately no, this issue is currently being worked on.

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.2.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.2.0) :rocket:
