### ISSUE TITLE
Add dependabot.yml

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/query-tool#90]
See https://github.com/neurobagel/old-query-tool/blob/main/.github/dependabot.yml from Vue implementation of query tool for reference.

**Comment by Sauradip07** [comment]
I want to work on this issue

**Comment by rmanaem** [comment]
@Sauradip07 Feel free to address this issue.

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.2.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.2.0) :rocket:
