### ISSUE TITLE
[ENH] Adopt Error boundary

### ISSUE THREAD

**Issue by surchs** [neurobagel/query-tool#95]
We should use an error boundary in our app: https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary

TODO:

- [x] If app breaks horribly, show a simple "This should not have happened" page
- [x] include on the page a link to open an issue
- [x] if possible, see if the feedback scriptlet from appzi can be included on this page
- [x] put any interesting learnings about error boundaries into the dev-docs (e.g. link to a site with the interesting info is good enough)

**Comment by rmanaem** [comment]
![Image](https://github.com/user-attachments/assets/e3d1e506-1975-4f83-94dd-4e1dda1aff07)
